baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[menu]
 [[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1

[[menu.main]]
  name = 'About'
  url = '/blog/about-permanent-pixels/'
  weight = 2

[[menu.main]]
  name = 'Blog'
  url = '/blog/'
  weight = 3

[[menu.main]]
  name = 'Gallery'
  url = ''
  disabled = true
  weight = 4

[[menu.main]]
  name = 'Resources'
  url = '/resources/'
  weight = 5

disabledmenus = ['Resources']